services:
  # NestJS API Service
  - type: web
    name: agentplaces-api
    env: node
    buildCommand: cd backend && npm ci && npm run build
    startCommand: cd backend && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        value: mongodb+srv://agentplaces:AVfYJZzuaW9TsTg2@agentplaces.fi3xt9v.mongodb.net/agentplaces?retryWrites=true&w=majority&appName=AgentPlaces
      - key: REDIS_URL
        fromService:
          name: agentplaces-redis
          type: redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://kaplayan-atakan.github.io

  # Worker Service for Background Jobs
  - type: worker
    name: agentplaces-worker
    env: node
    buildCommand: cd backend && npm ci && npm run build
    startCommand: cd backend && npm run start:worker
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://agentplaces:AVfYJZzuaW9TsTg2@agentplaces.fi3xt9v.mongodb.net/agentplaces?retryWrites=true&w=majority&appName=AgentPlaces
      - key: REDIS_URL
        fromService:
          name: agentplaces-redis
          type: redis
          property: connectionString
  # Redis Service
  - type: redis
    name: agentplaces-redis
    plan: free
    ipAllowList: []
